name: "Create package changelog entry"

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Title of the changelog entry"
        required: true
      category:
        description: "Category of the changelog entry"
        required: true
      version:
        description: "Version of the package"
        required: true
      changelog:
        description: "Changelog contents"
        required: true
      assignee:
        description: "The assignee of the PR to be created"
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  create:
    name: "Create integrations changelog entry"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create Git branch
        run: |
          # Normalize Git branch name so it doesn't contain spaces or capital letters
          export NORMALIZED_PACKAGE_CATEGORY=$(echo "$PACKAGE_CATEGORY" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
          echo "NORMALIZED_PACKAGE_CATEGORY=$NORMALIZED_PACKAGE_CATEGORY" >> $GITHUB_ENV
          BRANCH_NAME="$NORMALIZED_PACKAGE_CATEGORY-$PACKAGE_VERSION"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

          git checkout -b "$BRANCH_NAME"
        env:
          PACKAGE_CATEGORY: ${{ inputs.category }}
          PACKAGE_VERSION: ${{ inputs.version }}

      - name: Create changelog entry file
        run: |
          # Create changelog entry directory
          changelog_dir="posts/changelog/$(date +%Y)"
          mkdir -p "$changelog_dir"
          # Create changelog file based on template
          cat support/package-changelog-template.mdx | envsubst > "$changelog_dir/$(date +%Y-%m-%d)-${{ env.NORMALIZED_PACKAGE_CATEGORY }}-$PACKAGE_VERSION.mdx"
        env:
          CHANGELOG_TITLE: ${{ inputs.title }}
          CHANGELOG_CATEGORY: ${{ inputs.category }}
          PACKAGE_VERSION: ${{ inputs.version }}
          CHANGELOG_TEXT: ${{ inputs.changelog }}

      - name: Commit and push changelog entry
        run: |
          git add .
          git commit \
            -m 'Add changelog entry for ${{ github.event.inputs.category }} ${{ github.event.inputs.version }}' \
            -m 'Contents supplied by the GitHub Action API call.' \
            -m 'Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>'
          git push origin "${{ env.BRANCH_NAME }}"

      - name: Make Pull Request
        run: |
          gh pr create --fill --label "writing" --assignee "${{ inputs.assignee }}" --reviewer "${{ inputs.assignee }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
